#!/bin/bash

start()
{
  echo Starting TradingBot...
  cd scripts
  python3 trading_bot.py & echo $! > pid.txt
}

stop()
{
  echo Stopping TradingBot...
  cd scripts
  cat pid.txt | xargs kill
  rm pid.txt
}

close-positions()
{
  echo Starting TradingBot to close positions...
  cd scripts
  python3 trading_bot.py -c & echo $! > pid.txt
}

test()
{
  echo Running unit test with pytest...
  pytest
}

case $1 in
  start|stop|close-positions|test) "$1" ;;
esac
