#!/bin/bash

start()
{
  echo Starting TradingBot...
  cd src
  python3 main.py & echo $! > pid.txt
}

stop()
{
  echo Stopping TradingBot...
  cd src
  cat pid.txt | xargs kill
  rm pid.txt
}

close_positions()
{
  echo Starting TradingBot to close positions...
  cd src
  python3 main.py -c &
}

install_deps()
{
  echo Installing dependencies...
  pip install -r requirements.txt
}

test()
{
  echo Running unit test with pytest...
  install_deps
  sphinx-build -nWT -b dummy doc doc/_build/html
  pytest
}

start_docker()
{
  echo Starting TradingBot in a Docker container...
  LOG_DIR=$HOME/.TradingBot/log
  SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
  CONTAINER_NAME=dkr_trading_bot
  IMAGE=python:3
  mkdir -p $LOG_DIR
  docker run -dit --rm --name $CONTAINER_NAME -v $SCRIPT_DIR:/app -v $LOG_DIR:/root/.TradingBot/log $IMAGE /bin/bash app/run_docker.sh
}

test_docker()
{
  echo Running unit test with pytest in a Docker container...
  echo Testing against Python 3.4...
  docker run -it --rm -v $(pwd):/app python:3.4 /bin/bash -cx "cd app && ./trading_bot_ctl test"
  echo Testing against Python 3.5...
  docker run -it --rm -v $(pwd):/app python:3.5 /bin/bash -cx "cd app && ./trading_bot_ctl test"
  echo Testing against Python 3.6...
  docker run -it --rm -v $(pwd):/app python:3.6 /bin/bash -cx "cd app && ./trading_bot_ctl test"
  echo Testing against Python 3 latest...
  docker run -it --rm -v $(pwd):/app python:3 /bin/bash -cx "cd app && ./trading_bot_ctl test"
}

docs()
{
  sphinx-build -nWT -b html doc doc/_build/html
}

help()
{
  echo "Invalid command!"
  echo "Try with:"
  echo "  help - Show this help message"
  echo "  start - Start TradingBot"
  echo "  stop - Stop TradingBot"
  echo "  close_positions - Close all open positions and stop TradingBot"
  echo "  install_deps - Install TradingBot dependencies"
  echo "  test - Run TradingBot automatic test suite"
  echo "  test_docker - Run TradingBot automatic test suite inside docker containers"
  echo "  start_docker - Run TradingBot in a docker container"
  echo "  docs - Build TradingBot documentation"
}

case $1 in
  start|stop|close_positions|install_deps|test|test_docker|start_docker|docs) "$1" ;;
  *) help ;;
esac
